remove vis restriction for local and shared resources
rtic-rs/rtic pull request #730
Opened 2023-04-11 20:10 UTC by andrewgazelka

2023-04-12 07:22 UTC, korken89 requested changes
Thanks for the PR! I see one UI test is now panicking the macro, could you have a look at fixing that?

2023-04-12 07:22 UTC, korken89 commented on rtic-macros/ui/shared-pub.stderr
Specifically this one

2023-04-12 16:31 UTC, andrewgazelka commented on rtic-macros/ui/shared-pub.stderr
What action do you suggest I take? My PR has no impact on the error. 
https://github.com/rtic-rs/rtic/blob/89e060d0c1e7d34aa4751e10b4ea1ae3c727adf3/rtic-macros/src/syntax/parse/app.rs#L435-L436
If `x` were not public, it would have triggered a panic before my commit.

2023-04-12 18:48 UTC, korken89 commented on rtic-macros/ui/shared-pub.stderr
After taking a closer look at the test case, I'd just remove it. Lets not complicate it.

2023-04-12 22:20 UTC, andrewgazelka commented on rtic-macros/ui/shared-pub.stderr
@korken89 fixed :)

2023-04-13 05:37 UTC, korken89 approved these changes
Looks good, thanks!

bors merge

2023-04-13 05:41 UTC, merged