relax rtic-time generics
rtic-rs/rtic pull request #752
Opened 2023-05-17 05:36 UTC by burrbull

2023-05-20 08:36 UTC, datdenkikniet commented
I think this is a pretty good idea.

For clarity, we should perhaps rename the `TimerQueue` to `PriorityQueue` (since that is what it becomes with this relaxation), and add a `pub type TimerQueue<M> = PriorityQueue<<M as Monotonic>::Instant>` to clarify the "difference"?

2023-05-20 10:06 UTC, datdenkikniet requested changes

2023-05-20 10:06 UTC, datdenkikniet commented on rtic-time/src/lib.rs
> -impl<Mono: Monotonic> TimerQueue<Mono> {
I think we should rename `TimerQueue` to `PriorityQueue` and add a type alias similar to `type TimerQueue<T> = PriorityQueue<<T as Monotonic>::Instant>`

2024-04-13 14:02 UTC, Finomnis commented
Might collide with and/or become obsolete through #874.

2024-04-13 14:05 UTC, closed without merging