Signal ergo minor fixes
rtic-rs/rtic pull request #986
Opened 2024-10-23 17:15 UTC by SebKuzminsky

This fixes a couple of docs typos and derives Debug for Signal, SignalReader, and SignalWriter (and CriticalSectionWakerRegistration).

Having Debug available enables e.g. `my_task::spawn(my_signal_reader).unwrap();`

2024-10-23 18:11 UTC, korken89 requested changes
Thank you for the PR!

Deriving `Debug` does however not look like the correct thing to do as the underlying datastructures are not made for being printable.
Can you change to implement `Debug` manually on `SignalReader`/`SignalWriter` and just have it print something along the lines of `SignalWriter { .. }`?

2024-10-23 18:13 UTC, SebKuzminsky commented
Ok, will do!

2024-10-23 18:43 UTC, SebKuzminsky commented
I deviated from your suggestion a little bit:
```
my_signal_reader: SignalReader<u16>{ .. }
```
I'm happy to take the type out if you prefer, lmk.

2024-10-23 18:44 UTC, korken89 commented
That's fine, can you have a look at the failing test? I think it's just a `cargo fmt` missing.

2024-10-23 18:51 UTC, SebKuzminsky commented
That fixed it, only took 3 tries :roll_eyes: 
I see some new stuff went into `master`, do you want me to rebase?
Thanks for your patience and guidance...

2024-10-23 18:54 UTC, korken89 approved these changes

2024-10-23 18:55 UTC, korken89 commented
Thank you for the improvement, and no worries!

2024-10-23 18:55 UTC, merged

2024-10-29 15:29 UTC, AdinAck commented
Haha, fascilitates, facilitates, tomato tomAto! 😅

Thanks!